- hosts: localhost
  gather_facts: False
  connection: local
  vars:
    host: 
    vmware_username: 
    vmware_password: 
    datacenter: 
    datastore: datastore1
    network: VM Network
    template: 
    vmcluster: 
    vm_name: 
    customize_spec: RHEL7
    folder_name: vms
    notes: Created by Ansible
  tasks:

    - name: Create VM from template
      vmware_guest:
        hostname: "{{ host }}"
        username: "{{ vmware_username }}"
        password: "{{ vmware_password }}"
        datacenter: "{{ datacenter }}"
        name: "{{ vm_name }}"
        folder: "{{ folder_name }}"
        template_src: "{{ template }}"
        cluster: "{{ vmcluster }}"
        customization_spec: "{{ customize_spec }}"
