- hosts: localhost
  gather_facts: False
  connection: local
  vars:
    flavor:
    vm_size:
      small:
        cpu: 2
        memory: 2048
        size: 50
      medium:
        cpu: 4
        memory: 4096
        size: 100
    datastore: datastore1
#   customize_spec: RHEL7
    folder_name: 'Discovered virtual machine'
    notes: Created by Ansible
#   vm_name: "{{ survey_vm_name.split('\n') }}"
    
    
  tasks:

    - name: Create VM from template
      vmware_guest:
        hostname: "{{ host }}"
        username: "{{ vmware_username }}"
        password: "{{ vmware_password }}"
        validate_certs: False
        datacenter: "{{ datacenter }}"
        name: "{{ vm_name }}"
        folder: "{{ folder_name }}"
        template_src: "{{ template }}"
        cluster: "{{ vmcluster }}"
#       customization_spec: "{{ customize_spec }}"
#       wait_for_ip_address: yes
        customization:
          hostname: "{{ vm_name }}"
          domain: "{{ domain_name }}"
        disk:
        - disk2:
          size_gb: "{{ vm_size[flavor]['size'] }}"
          autoselect_datastore: true
        hardware:
          num_cpus: "{{ vm_size[flavor]['cpu'] }}"
          memory_mb: "{{ vm_size[flavor]['memory'] }}"
        networks:
          - name: VM Network
            ip: "{{ ip_addr }}"
            netmask: "{{ net_mask }}"
            gateway: "{{ gate_way }}"
#            mac: aa:bb:dd:aa:00:14
#           domain: my_domain
            dns_servers:
            - 192.168.1.1
#           - 192.168.1.2
#         - vlan: 1234
#           type: dhcp
#     loop: "{{ vm_name }}"
#        - { name: "{{ vm_name }}", ip: "{{ vm_ip }}" }

