- hosts: localhost
  gather_facts: False
  connection: local
  vars:
    flavor:
    vm_size:
      small:
        cpu: 2
        memory: 2048
        size: 50
      medium:
        cpu: 4
        memory: 4096
        size: 100
    datastore: datastore1
#   customize_spec: RHEL7
#   notes: Created by Ansible
#   vm_name: "{{ survey_vm_name.split('\n') }}"
    
    
  tasks:

    - name: Create VM from template
      vmware_guest:
        hostname: "{{ host }}"
        username: "{{ vmware_username }}"
        password: "{{ vmware_password }}"
        validate_certs: False
        datacenter: "{{ datacenter }}"
        name: "{{ vm_name }}"
        folder: DatacenterA/vm/production
        template_src: "{{ template }}"
        cluster: "{{ vmcluster }}"
#       customization_spec: "{{ customize_spec }}"
#       wait_for_ip_address: yes
#       customization:
#         hostname: "{{ vm_name }}"
#         domain: "{{ domain_name }}"
#       disk:
#       - disk2:
#         size_gb: "{{ vm_size[flavor]['size'] }}"
#         autoselect_datastore: true
#       hardware:
#         num_cpus: "{{ vm_size[flavor]['cpu'] }}"
#         memory_mb: "{{ vm_size[flavor]['memory'] }}"
#       networks:
#         - name: VM Network
#           ip: "{{ ip_addr }}"
#           netmask: "{{ net_mask }}"
#           gateway: "{{ gate_way }}"
#            mac: aa:bb:dd:aa:00:14
#           domain: my_domain
#           dns_servers:
#           - 192.168.1.1
#           - 192.168.1.2
#         - vlan: 1234
#           type: dhcp
        state: poweredon
#     loop: "{{ vm_name }}"
#        - { name: "{{ vm_name }}", ip: "{{ vm_ip }}" }

#   - name: Wait 300 seconds, but only start checking after 60 seconds
#     wait_for_connection:
#       delay: 60
#       timeout: 300

#   - name: Wait for server to restart
#     local_action:
#       module: wait_for
#         host="{{ ip_addr }}"
#         port=22
#         delay=30
#         timeout=300
