- hosts: localhost
  gather_facts: False
  connection: local
  vars:
    flavor:
    vm_size:
      small:
        cpu: 2
        memory: 2048
      medium:
        cpu: 4
        memory: 4096
    host: 
    vmware_username: 
    vmware_password: 
    datacenter: 
    datastore: datastore1
    template: 
    vmcluster: 
    customize_spec: RHEL7
    folder_name: vms
    notes: Created by Ansible
    vm_name: "{{ survey_vm_name.split('\n') }}"
    vm_ip: "{{ survey_vm_ip.split('\n') }}"
    
    
  tasks:

    - name: Create VM from template
      vmware_guest:
        hostname: "{{ host }}"
        username: "{{ vmware_username }}"
        password: "{{ vmware_password }}"
        datacenter: "{{ datacenter }}"
        name: "{{ item.name }}"
        folder: "{{ folder_name }}"
        template_src: "{{ template }}"
        cluster: "{{ vmcluster }}"
        customization_spec: "{{ customize_spec }}"
        hardware:
          num_cpu: "{{ vm_size[flavor]['cpu'] }}"
          memory_mb: "{{ vm_size[flavor]['memory'] }}"
        networks:
          - name: VM Network
            ip: "{{ item.ip }}"
            netmask: 255.255.255.0
            gateway: 192.168.1.1
#            mac: aa:bb:dd:aa:00:14
#           domain: my_domain
#           dns_servers:
#           - 192.168.1.1
#           - 192.168.1.2
#         - vlan: 1234
#           type: dhcp
      loop:
         - { name: "{{ vm_name }}", ip: "{{ vm_ip }}" }

