- hosts: localhost
  gather_facts: False
  connection: local
  vars:
    vcenter_hostname: 192.168.100.101
    vcenter_user: administrator@vsphere.local
    vcenter_pass: P@ssw0rd
    datacenter: SiteA
    datastore: datastore1
    network: VM Network
    template: vcsa
    vmcluster: ClusterA
    name: testvm
    folder_name: vms
    notes: Created by Ansible
  tasks:
    - name: check for required variables
      fail: msg="Must pass name to -e"
      when: name is not defined

    - name: Check for vSpehre access parameters
      fail: msg="Must set vcenter_user and vcenter_pass in Credentials"
      when: (vcenter_user is not defined) or (vcenter_pass is not defined)

    - name: Create VM from template
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        datacenter: "{{ datacenter }}"
        is_template: yes
        name: "{{ name }}"
        folder: "{{ folder_name }}"
        template_src: "{{ template }}"
        cluster: "{{ vmcluster }}"

