- hosts: localhost
  gather_facts: False
  connection: local
  vars:
    flavor:
    vm_size:
      small:
        cpu: 2
        memory: 2048
      medium:
        cpu: 4
        memory: 4096
    host: 
    vmware_username: 
    vmware_password: 
    datacenter: 
    datastore: datastore1
    network: VM Network
    template: 
    vmcluster: 
    customize_spec: RHEL7
    folder_name: vms
    notes: Created by Ansible
    vm_name: "{{ survey_vm_name.split('\n') }}"
    
  tasks:

    - name: Create VM from template
      vmware_guest:
        hostname: "{{ host }}"
        username: "{{ vmware_username }}"
        password: "{{ vmware_password }}"
        datacenter: "{{ datacenter }}"
        name: "{{ item }}"
        folder: "{{ folder_name }}"
        template_src: "{{ template }}"
        cluster: "{{ vmcluster }}"
        customization_spec: "{{ customize_spec }}"
        hardware:
          num_cpu: "{{ vm_size[flavor]['cpu'] }}"
          memory_mb: "{{ vm_size[flavor]['memory'] }}"
      loop:
        "{{ vm_name }}"

