- hosts: localhost
  gather_facts: False
  connection: local
  vars:

    datacenter: SiteA
    datastore: datastore1
    network: VM Network
    template: vcsa
    vmcluster: ClusterA
    name: testvm2
    folder_name: vms
    notes: Created by Ansible
    
    guest_domain: mydomain
  tasks:
    - name: check for required variables
      fail: msg="Must pass name to -e"
      when: name is not defined



    - name: Create VM from template
      vmware_guest:
        hostname: "{{ lookup("env", "VMWARE_HOST") }}"
        username: "{{ lookup("env", "VMWARE_USER") }}"
        password: "{{ lookup("env", "VMWARE_PASSWORD") }}"
        datacenter: "{{ datacenter }}"
        name: "{{ name }}"
        folder: "{{ folder_name }}"
        template_src: "{{ template }}"
        cluster: "{{ vmcluster }}"
        
        networks:
          - name: VM Network
            ip: 192.168.10.11
            netmask: 255.255.255.0
        wait_for_ip_address: True
        customization:
          domain: "{{ guest_domain }}"
          dns_servers:
            - 8.9.9.9
            - 7.8.8.9
          dns_suffix:
            - example.com
            - example2.com

